import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Wallet,keccak256,toUtf8Bytes,solidityPackedKeccak256,ZeroAddress,ZeroHash,Signature,Interface,AbiCoder } from 'ethers';
import { inspectOffchain } from '../lib/offchain';
import { prepareProof,GIWA_SIGNER_ROOT } from '../lib/proof-policy';
import { CONTRACTS,GIWA_PROOF,NETWORK } from '../lib/giwa';
import { EAS_WRITE_ABI,inspectTransaction } from '../lib/eas-calldata';
const signer=new Wallet('0x'+'11'.repeat(32));
async function signed(version:number){const message:Record<string,unknown>={...(version?{version}:{}),schema:keccak256(toUtf8Bytes('uint256 balance')),recipient:signer.address,time:1,expirationTime:0,revocable:true,refUID:ZeroHash,data:AbiCoder.defaultAbiCoder().encode(['uint256'],[100]),...(version===2?{salt:keccak256(toUtf8Bytes('unique high entropy salt'))}:{})};const fields=[...(version?[{name:'version',type:'uint16'}]:[]),{name:'schema',type:'bytes32'},{name:'recipient',type:'address'},{name:'time',type:'uint64'},{name:'expirationTime',type:'uint64'},{name:'revocable',type:'bool'},{name:'refUID',type:'bytes32'},{name:'data',type:'bytes'},...(version===2?[{name:'salt',type:'bytes32'}]:[])];const primaryType=version?'Attest':'Attestation';const types={[primaryType]:fields};const domain={name:'EAS Attestation',version:'1.4.1-beta.3',chainId:91342,verifyingContract:CONTRACTS.EAS};const uid=solidityPackedKeccak256([...(version?['uint16']:[]),'bytes','address','address','uint64','uint64','bool','bytes32','bytes',...(version===2?['bytes32']:[]),'uint32'],[...(version?[version]:[]),toUtf8Bytes(String(message.schema)),signer.address,ZeroAddress,1,0,true,ZeroHash,message.data,...(version===2?[message.salt]:[]),0]);return{version,uid,domain,primaryType,types,message,signature:Signature.from(await signer.signTypedData(domain,types,message)).toJSON(),attester:signer.address};}
for(const version of [0,1,2])test(`EAS v${version} signature recovers expected issuer`,async()=>{const a=await signed(version);const r=inspectOffchain(a,signer.address);assert.equal(r.signer,signer.address);assert.equal(r.expectedIssuerChecked,true);assert.equal(r.expired,false);});
test('modified credential rejected, including wrong chain and wrong expected issuer',async()=>{const a=await signed(2);assert.throws(()=>inspectOffchain({...a,message:{...a.message,data:'0x'}}),/UID/);assert.throws(()=>inspectOffchain({...a,domain:{...a.domain,chainId:1}}),/다른 체인/);assert.throws(()=>inspectOffchain(a,Wallet.createRandom().address),/발행자/);assert.throws(()=>inspectOffchain({...a,domain:{...a.domain,verifyingContract:ZeroAddress}}),/GIWA/);});
test('unrecognized EIP712 types cannot become an EAS credential',async()=>{const a=await signed(1);assert.throws(()=>inspectOffchain({...a,types:{Attest:[{name:'arbitrary',type:'string'}]}}),/구조/);});
function proof(){const scope='dojang-scan:test-request:unique';const groups=[keccak256(toUtf8Bytes('signal')),GIWA_SIGNER_ROOT,keccak256(toUtf8Bytes(scope)),keccak256(toUtf8Bytes('nullifier'))];const publicInputs=groups.flatMap(s=>Array.from(Buffer.from(s.slice(2),'hex'),n=>'0x'+n.toString(16)));return{scope,response:{circuit:'giwa_attestation',chainId:91342,verifierAddress:GIWA_PROOF.verifier,status:'completed',proof:'0x1122',publicInputs}};}
test('proof policy pins verifier and circuit and binds requested scope',()=>{const {scope,response}=proof();assert.equal(prepareProof(response,scope).publicInputs.length,128);assert.throws(()=>prepareProof({...response,verifierAddress:ZeroAddress},scope),/프로필/);assert.throws(()=>prepareProof({...response,chainId:1},scope),/프로필/);assert.throws(()=>prepareProof(response,'another-request'),/scope/);assert.throws(()=>prepareProof({...response,publicInputs:Array(192).fill('0x00')},scope),/128/);});
test('non-byte inputs and untrusted issuer roots are rejected',()=>{const {scope,response}=proof();const bytes=[...response.publicInputs];bytes[32]='0x100';assert.throws(()=>prepareProof({...response,publicInputs:bytes},scope),/byte/);bytes[32]='0x00';assert.throws(()=>prepareProof({...response,publicInputs:bytes},scope),/root/);});
test('transaction insight checks target and chain before decoding',()=>{const abi=new Interface(EAS_WRITE_ABI);const data=abi.encodeFunctionData('attest',[{schema:keccak256(toUtf8Bytes('schema')),data:{recipient:signer.address,expirationTime:1234,revocable:true,refUID:ZeroHash,data:AbiCoder.defaultAbiCoder().encode(['bool'],[true]),value:0}}]);const result=inspectTransaction(CONTRACTS.EAS,NETWORK.chainId,data,'bool isVerified');assert.equal(result.action,'attest');assert.equal(result.recipient,signer.address);assert.equal(result.fields?.[0].value,'true');assert.throws(()=>inspectTransaction(ZeroAddress,NETWORK.chainId,data),/트랜잭션/);assert.throws(()=>inspectTransaction(CONTRACTS.EAS,1,data),/트랜잭션/);});
