'use client';
import { useEffect, useRef, useState } from 'react';
import { Fingerprint, Smartphone, ShieldCheck, FileJson, ExternalLink, Download, Copy, AlertCircle, CheckCircle2, ScanLine, LockKeyhole, RefreshCw } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { toast } from 'sonner';
import { type ProofportSDK,type RelayProofRequest,type RelayProofResult } from '@zkproofport-app/sdk';
import { type SchemaRecord,GIWA_PROOF,CONTRACTS,NETWORK,short } from '@/lib/giwa';
import { connectWallet } from '@/lib/wallet';
import { inspectOffchain } from '@/lib/offchain';
import { inspectTransaction } from '@/lib/transaction-insight';
import { getData,Badge,CopyButton } from './scan-ui';
import { downloadJSON } from './scan-detail';
type CheckResult={valid:boolean;block:number;scope:string;signal:string;nullifier:string;warning:string};
export default function ProofStudio(){
 const [tab,setTab]=useState('request');const [scope,setScope]=useState('');const [request,setRequest]=useState<RelayProofRequest|null>(null);const [result,setResult]=useState<RelayProofResult|null>(null);const [qr,setQr]=useState('');const [requestBusy,setRequestBusy]=useState(false);const [requestError,setRequestError]=useState('');const [consent,setConsent]=useState(false);const [requestStatus,setRequestStatus]=useState('');const sdkRef=useRef<ProofportSDK|null>(null);const requestScope=useRef('');const deadline=useRef(0);const poll=useRef<ReturnType<typeof setInterval>|null>(null);
 const [proofText,setProofText]=useState('');const [verifyScope,setVerifyScope]=useState('');const [verifyBusy,setVerifyBusy]=useState(false);const [verification,setVerification]=useState<CheckResult|null>(null);const [verifyError,setVerifyError]=useState('');
 const [offchainText,setOffchainText]=useState('');const [issuer,setIssuer]=useState('');const [offBusy,setOffBusy]=useState(false);const [offResult,setOffResult]=useState<Record<string,unknown>|null>(null);const [offError,setOffError]=useState('');
 const [calldata,setCalldata]=useState('');const [insight,setInsight]=useState<Record<string,unknown>|null>(null);const [insightError,setInsightError]=useState('');const [insightBusy,setInsightBusy]=useState(false);
 useEffect(()=>{setScope('dojang-scan:'+window.location.hostname);return()=>{if(poll.current)clearInterval(poll.current);sdkRef.current?.disconnect?.();};},[]);
 function stop(){if(poll.current)clearInterval(poll.current);poll.current=null;setRequestStatus('조회 중지');}
 async function start(){setConsent(false);stop();setRequestBusy(true);setRequestError('');setResult(null);setVerification(null);setRequest(null);setQr('');try{const {ProofportSDK}=await import('@zkproofport-app/sdk');const {signer}=await connectWallet();const sdk=ProofportSDK.create();sdk.setSigner(signer);sdkRef.current=sdk;const uniqueScope=scope.trim()+':'+crypto.randomUUID();requestScope.current=uniqueScope;const r=await sdk.createRelayRequest('giwa_attestation',{scope:uniqueScope},{dappName:'Dojang Scan',message:'GIWA Sepolia 테스트 attester 주소 소유 증명. 실제 Dojang 발급 자격의 증명이 아닙니다.',nonce:crypto.randomUUID()});setRequest(r);setQr(await sdk.generateQRCode(r.deepLink));setRequestStatus('모바일 앱에서 증명 대기');deadline.current=Date.now()+10*60*1000;let running=false;poll.current=setInterval(async()=>{if(running)return;if(Date.now()>deadline.current){stop();setRequestStatus('대기 시간이 만료되었습니다.');return;}running=true;try{const response=await sdk.pollResult(r.requestId);if(response.requestId!==r.requestId)throw new Error('다른 요청의 결과가 반환되었습니다.');setRequestStatus(response.status);if(response.status==='completed'){stop();setResult(response);setProofText(JSON.stringify(response,null,2));setVerifyScope(uniqueScope);setRequestStatus('증명 수신 · 아직 검증하지 않음');}else if(response.status==='failed'){stop();setRequestError(response.error||'모바일 증명에 실패했습니다.');}}catch(e){stop();setRequestError((e as Error).message);}finally{running=false;}},3000);}catch(e){setRequestError((e as Error).message);}finally{setRequestBusy(false);}}
 async function verify(){setVerifyBusy(true);setVerifyError('');setVerification(null);try{const response=JSON.parse(proofText);const r=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({response,scope:verifyScope})});const d=await r.json() as CheckResult & {error?:string};if(!r.ok)throw new Error(d.error);setVerification(d);}catch(e){setVerifyError((e as Error).message);}finally{setVerifyBusy(false);}}
 async function verifyOffchain(){setOffBusy(true);setOffError('');setOffResult(null);try{const local=inspectOffchain(JSON.parse(offchainText),issuer.trim());const status=await getData('offchain',{issuer:local.signer,uid:local.uid});if(status.easVersion!==local.domainVersion)throw new Error('서명 도메인 버전이 현재 GIWA EAS 버전과 다릅니다. 별도 버전 정책을 검토해 주세요.');setOffResult({...local,...status,acceptable:!local.expired&&!local.futureIssued&&status.revocationTime===0});}catch(e){setOffError((e as Error).message);}finally{setOffBusy(false);}}
 async function decode(){setInsightBusy(true);setInsightError('');setInsight(null);try{const first=inspectTransaction(CONTRACTS.EAS,NETWORK.chainId,calldata.trim());const s:SchemaRecord=await getData('schema',{uid:first.schema});setInsight(inspectTransaction(CONTRACTS.EAS,NETWORK.chainId,calldata.trim(),s.definition));}catch(e){setInsightError((e as Error).message);}finally{setInsightBusy(false);}}
 return <section className="view-section studio"><div className="studio-heading"><div className="proof-orbit"><Fingerprint size={26}/></div><div><span className="section-kicker">PROOF STUDIO</span><h2>탐색에서, 증명으로.</h2></div><Badge variant="red">GIWA SEPOLIA ONLY</Badge></div><Tabs value={tab} onValueChange={setTab}><TabsList className="studio-tabs"><TabsTrigger value="request"><Smartphone size={16}/>모바일 증명</TabsTrigger><TabsTrigger value="verify"><ShieldCheck size={16}/>ZK 검증</TabsTrigger><TabsTrigger value="offchain"><FileJson size={16}/>오프체인 도장</TabsTrigger><TabsTrigger value="insight"><ScanLine size={16}/>지갑 인사이트</TabsTrigger></TabsList>
 <TabsContent value="request"><div className="studio-grid"><div className="studio-panel"><span className="section-kicker">01 / REQUEST A PROOF</span><h3>모바일 앱에서 증명 받기</h3><p>ZKProofport가 기기에서 증명을 생성하고 공개 입력과 proof를 돌려줍니다.</p><div className="notice"><AlertCircle size={17}/><span><strong>현재는 CIP-4 테스트 프로필입니다.</strong> GIWA 앱의 Developer Mode가 필요하며 MockGiwaAttester만 지원합니다. 실제 UPbit Dojang이나 은행·신분 자격 도장을 증명하지 않습니다.</span></div><label className="input-label" htmlFor="scope">서비스 scope</label><input className="form-input" id="scope" value={scope} onChange={e=>setScope(e.target.value)}/><p className="fine-print">각 요청에 고유 scope를 붙여 이전 요청의 proof가 혼동되지 않게 합니다.</p><button className="primary" disabled={requestBusy||!scope.trim()} onClick={()=>setConsent(true)}>{requestBusy?<RefreshCw size={16} className="spinning"/>:<Smartphone size={16}/>}증명 요청 만들기</button>{requestError&&<div className="notice danger" role="alert">{requestError}</div>}<div className="profile-info"><span>회로</span><code>giwa_attestation</code><span>고정 verifier</span><a className="mono" href={`${NETWORK.explorer}/address/${GIWA_PROOF.verifier}`} target="_blank" rel="noreferrer">{short(GIWA_PROOF.verifier)}<ExternalLink size={12}/></a><span>상태</span><Badge>Planned · PoC</Badge></div></div><div className="studio-panel qr-panel">{request?<><Badge variant="blue">{requestStatus}</Badge>{qr&&<img src={qr} width={220} height={220} alt="ZKProofport 증명 요청 QR 코드"/>}<a className="primary" href={request.deepLink}>ZKProofport 앱 열기</a><span className="mono">{short(request.requestId,10)}</span><button className="text-button" onClick={()=>navigator.clipboard.writeText(request.deepLink).then(()=>toast.success('요청 링크를 복사했습니다.'))}><Copy size={14}/>요청 링크 복사</button><button className="text-button" onClick={stop}>대기 중지</button>{result&&<button className="secondary-button" onClick={()=>setTab('verify')}>수신한 proof 검증하기</button>}</>:<><Smartphone size={42}/><h3>앱으로 스캔하세요.</h3><p>요청을 만들면 QR과 앱 링크가 나타납니다.<br/>proof 수신 후 검증을 실행하세요.</p><div className="mini-steps"><span>요청</span><span>기기 내 생성</span><span>검증</span></div></>}</div></div></TabsContent>
 <TabsContent value="verify"><div className="studio-grid"><div className="studio-panel"><span className="section-kicker">02 / VERIFY THE STATEMENT</span><h3>GIWA ZK proof 확인</h3><p>고정 verifier, 테스트 발행자 root, 공개 입력 128개와 scope를 함께 확인합니다.</p><label className="input-label" htmlFor="verify-scope">기대한 scope</label><input className="form-input" id="verify-scope" value={verifyScope} onChange={e=>setVerifyScope(e.target.value)} placeholder="요청에 사용한 scope"/><JsonInput id="proof-json" label="ProofResponse JSON" value={proofText} setValue={setProofText}/><button className="primary" disabled={verifyBusy||!proofText||!verifyScope} onClick={verify}>{verifyBusy?<RefreshCw className="spinning" size={16}/>:<ShieldCheck size={16}/>}온체인 verifier로 확인</button><p className="fine-print">읽기 전용 eth_call입니다. 가스나 트랜잭션 서명이 필요하지 않습니다.</p>{verifyError&&<div className="notice danger" role="alert">{verifyError}</div>}</div><div className="studio-panel result-panel">{verification?<><div className={'result-icon '+(verification.valid?'good':'bad')}>{verification.valid?<CheckCircle2 size={33}/>:<AlertCircle size={33}/>}</div><h3>{verification.valid?'암호학적 검증 통과':'검증되지 않은 proof'}</h3><p>GIWA Sepolia 블록 {verification.block.toLocaleString()}의 verifier 응답입니다.</p><div className="field-list"><div><span>Scope hash</span><code>{verification.scope}</code></div><div><span>Nullifier</span><code>{verification.nullifier}</code></div></div><div className="notice">{verification.warning} 이 결과만으로 서비스 이용 자격을 부여하지 마세요.</div><button className="secondary-button" onClick={()=>downloadJSON(verification,'giwa-proof-verification.json')}><Download size={14}/>검증 결과 저장</button></>:<><ShieldCheck size={38}/><h3>증명의 의미까지 확인합니다.</h3><p>수신한 JSON 또는 보유한 proof를 입력하세요. 수학적으로 유효한 proof와 실제 Dojang 자격은 별개의 검증입니다.</p></>}</div></div></TabsContent>
 <TabsContent value="offchain"><div className="studio-grid"><div className="studio-panel"><span className="section-kicker">OFFCHAIN, VERIFIED LOCALLY</span><h3>서명된 오프체인 도장</h3><p>EAS SDK JSON을 가져와 서명·UID·만료·GIWA 도메인을 확인합니다.</p><div className="local-note"><LockKeyhole size={17}/>원문과 서명은 브라우저 안에서 처리됩니다. 서버에는 공개 UID와 서명자 주소만 전달합니다.</div><label className="input-label" htmlFor="expected-issuer">기대한 발행자 주소 (선택)</label><input className="form-input" id="expected-issuer" value={issuer} onChange={e=>setIssuer(e.target.value)} placeholder="0x… / 비우면 서명자만 복원"/><JsonInput id="offchain-json" label="SignedOffchainAttestation JSON" value={offchainText} setValue={setOffchainText}/><button className="primary" onClick={verifyOffchain} disabled={offBusy||!offchainText}>{offBusy?<RefreshCw className="spinning" size={16}/>:<ShieldCheck size={16}/>}서명과 상태 확인</button>{offError&&<div className="notice danger" role="alert">{offError}</div>}</div><div className="studio-panel result-panel">{offResult?<><div className={'result-icon '+(offResult.acceptable?'good':'bad')}><FileJson size={32}/></div><h3>{offResult.acceptable?'서명 유효 · 현재 취소 기록 없음':'서명 유효 · 사용 조건 미충족'}</h3><Badge variant={offResult.registeredIssuer?'success':'neutral'}>{offResult.registeredIssuer?'현재 등록 발행자':'등록 발행자 미확인'}</Badge><div className="field-list">{[['서명자',offResult.signer],['EAS UID',offResult.uid],['발행자 직접 지정',offResult.expectedIssuerChecked?'확인':'미지정'],['만료',offResult.expired?'만료됨':'미만료'],['온체인 타임스탬프',offResult.timestamp?'기록됨':'없음'],['온체인 취소',offResult.revocationTime?'취소됨':'현재 기록 없음']].map(([k,v])=><div key={String(k)}><span>{String(k)}</span><code>{String(v)}</code></div>)}</div><p className="fine-print">서명 유효성은 내용의 진실성을 보장하지 않습니다. 위임·오프체인 취소 정책은 별도로 확인해야 합니다.</p><button className="secondary-button" onClick={()=>{const {message,...publicReport}=offResult;downloadJSON(publicReport,'offchain-verification.json');}}><Download size={14}/>검증 결과 저장</button></>:<><FileJson size={38}/><h3>공개하지 않고 확인하세요.</h3><p>원본 JSON은 저장하지 않습니다. 체인 91342 · GIWA EAS · EAS 버전 0, 1, 2의 서명 형식을 지원합니다.</p></>}</div></div><BridgeDesign/></TabsContent>
 <TabsContent value="insight"><div className="studio-grid"><div className="studio-panel"><span className="section-kicker">WALLET TRANSACTION INSIGHTS</span><h3>서명 전에, 무엇을 하는지.</h3><p>EAS로 보낼 attest·revoke calldata를 사람이 읽을 수 있는 내용으로 해석합니다.</p><label className="input-label" htmlFor="calldata">GIWA EAS calldata</label><textarea className="json-input" id="calldata" value={calldata} onChange={e=>setCalldata(e.target.value)} placeholder="0xf17325e7…"/><div className="profile-info"><span>체인</span><code>91342</code><span>수신 컨트랙트</span><code>{short(CONTRACTS.EAS)}</code></div><button className="primary" onClick={decode} disabled={insightBusy||!calldata}>{insightBusy?<RefreshCw size={16} className="spinning"/>:<ScanLine size={16}/>}트랜잭션 해석</button>{insightError&&<div className="notice danger" role="alert">{insightError}</div>}</div><div className="studio-panel result-panel">{insight?<><Badge variant="blue">{String(insight.action).toUpperCase()}</Badge><h3>{insight.action==='attest'?'도장 발급':'도장 취소'}</h3><pre className="code-box">{JSON.stringify(insight,null,2)}</pre></>:<><ScanLine size={38}/><h3>MetaMask Snap의 역할</h3><p>Snap은 MetaMask에 기능을 추가하는 확장입니다. EAS Snap은 트랜잭션의 스키마와 내용을 서명 화면에 보여줍니다.</p><div className="notice">기존 EAS Snap의 공개 설정에는 GIWA가 없습니다. 위 도구는 GIWA용 인사이트를 내장하며, 실제 지갑 안에서 표시하려면 별도의 GIWA Snap 설치가 필요합니다.</div><a className="secondary-button" href="https://github.com/ethereum-attestation-service/eas-metamask-snap" target="_blank" rel="noreferrer">EAS Snap 소스<ExternalLink size={14}/></a></>}</div></div><div className="notice">이 도구는 트랜잭션을 전송하지 않습니다. 직접 EAS에 호출하는 attest·revoke를 지원하며 resolver·배치·위임 호출은 별도 해석이 필요합니다. GIWA용 Snap 소스는 프로젝트의 snaps/ 폴더에 포함되어 있습니다.</div></TabsContent>
 </Tabs><Dialog open={consent} onOpenChange={setConsent}><DialogContent><DialogHeader><DialogTitle>GIWA 테스트 증명 요청</DialogTitle><DialogDescription>브라우저 지갑으로 relay의 요청 challenge에 서명합니다. 가스나 자산 이동은 없습니다. relay에는 요청과 서명·지갑 주소가 전달됩니다.</DialogDescription></DialogHeader><div className="notice">GIWA 회로는 아직 공식 지원 전인 테스트용 PoC입니다. 실제 금융기관·신분 도장은 이 요청으로 증명할 수 없습니다.</div><button className="primary" onClick={start}>지갑으로 요청 서명</button></DialogContent></Dialog></section>;
}
function JsonInput({id,label,value,setValue}:{id:string;label:string;value:string;setValue:(value:string)=>void}){return <div className="json-field"><label className="input-label" htmlFor={id}>{label}</label><textarea className="json-input" id={id} value={value} onChange={e=>setValue(e.target.value)} placeholder="{ … }" spellCheck={false}/><label className="file-picker"><FileJson size={14}/>JSON 파일 가져오기<input type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>250000){toast.error('250KB 이하 JSON 파일을 사용해 주세요.');return;}void f.text().then(setValue);e.target.value='';}}/></label></div>;}
function BridgeDesign(){return <section className="bridge-design"><div><Badge variant="red">DESIGN PROFILE · NOT DEPLOYED</Badge><h2>오프체인 도장에서, 공개 가능한 사실만.</h2><p>오프체인 원문을 공개하지 않고도 조건 충족을 온체인에 남기는 경로입니다. 전용 회로와 승인된 verifier가 준비되기 전까지 등록은 활성화되지 않습니다.</p></div><div className="bridge-steps">{[{n:'01',title:'발행자 서명',text:'EAS EIP-712 원문 · 발행자 권한 · 자격 유효 기간'},{n:'02',title:'기기 내 ZK 증명',text:'서명 · 조건 · 소유권 · 최신 취소 root · scope'},{n:'03',title:'고정 verifier',text:'승인된 회로 · 공개 입력 · replay 방지'},{n:'04',title:'파생 도장',text:'조건 결과 · nullifier · 만료 · 프로필 ID만 기록'}].map(s=><div key={s.n}><span>{s.n}</span><h3>{s.title}</h3><p>{s.text}</p></div>)}</div><div className="notice">은행 잔액·증권 자산은 정확한 금액 대신 조건 충족을, 신분·전문 자격은 개인정보 대신 자격과 유효 기간을 공개하도록 확장할 수 있습니다. 원문 전체의 단순 해시를 무조건 공개하지 않으며, 저엔트로피 개인정보는 salted commitment로 보호해야 합니다.</div></section>;}
