'use client';
import { useEffect, useState } from 'react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { ExternalLink, Download, ShieldCheck, CheckCircle2, AlertCircle, Fingerprint, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { type Attestation, type SchemaRecord, NETWORK, ZERO, short } from '@/lib/giwa';
import { getData, CopyButton, Badge, Status } from './scan-ui';
export function downloadJSON(value: unknown, name: string) { const blob = new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export default function ScanDetail({ record, schema, close, goWallet, goSchema }: { record: Attestation | null; schema: SchemaRecord | null; close: () => void; goWallet: (address: string) => void; goSchema: (uid: string) => void }) {
 const [live, setLive] = useState<Attestation & { checkedBlock?: number; checkedAt?: string } | null>(record); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
 useEffect(() => { let ignore = false; setLive(record); setError(''); if (record) { setBusy(true); getData('attestation', { uid: record.uid }).then(d => { if (!ignore) setLive({ ...record, ...d }); }).catch(e => { if (!ignore) setError(e.message); }).finally(() => { if (!ignore) setBusy(false); }); } return () => { ignore = true; }; }, [record]);
 const a = live; const title = schema?.name ?? a?.schemaName ?? '도장';
 return <Sheet open={!!record || !!schema} onOpenChange={open => { if (!open) close(); }}><SheetContent className="detail-sheet"><SheetHeader><div className="detail-icon"><Fingerprint size={28}/></div><SheetTitle>{title}</SheetTitle><SheetDescription>{schema ? 'SchemaRegistry에서 확인한 스키마의 구조와 검증 경로입니다.' : 'EAS에 기록된 도장의 발행자, 데이터와 현재 상태를 확인하세요.'}</SheetDescription></SheetHeader><div className="detail-body">
 {schema ? <><div className="detail-status"><Badge variant={schema.current ? 'success' : 'neutral'}>{schema.current ? '현재 Dojang 스키마' : '이전 / 외부 스키마'}</Badge><Badge>{schema.category}</Badge></div><p>{schema.description}</p><Info label="EAS Schema UID" value={schema.uid}/>{schema.id && <Info label="Dojang Schema ID" value={schema.id}/>}<Info label="Resolver" value={schema.resolver}/><Info label="취소 가능" value={schema.revocable ? '가능' : '불가능'}/><h3>데이터 구조</h3><pre className="code-box">{schema.definition}</pre><div className="field-list">{schema.definition.split(',').map(v => <div key={v}><code>{v.trim().split(/\s+/)[1]}</code><span>{v.trim().split(/\s+/)[0]}</span></div>)}</div><a className="secondary-button" href={`${NETWORK.explorer}/address/${schema.resolver}`} target="_blank" rel="noreferrer">Resolver 보기<ExternalLink size={14}/></a><div className="notice">새 발행자가 같은 스키마를 사용해도 기관의 실제 신원과 신뢰 정책은 별도로 확인해야 합니다.</div></> : a ? <>
 <div className="detail-status"><Status value={a.status}/><Badge variant={a.dojang ? 'blue' : 'neutral'}>{a.dojang ? 'Dojang schema' : 'EAS'}</Badge>{busy && <RefreshCw size={14} className="spinning"/>}</div>{error && <div className="notice danger">최신 상태 재조회 실패: {error}</div>}
 <Info label="Attestation UID" value={a.uid}/><div className="trust-check"><ShieldCheck size={21}/><div><strong>{a.registeredIssuer ? '현재 등록된 Dojang 발행자' : '현재 등록 목록에 없는 발행자'}</strong><p>{a.registeredIssuer ? 'AttesterBook의 현재 주소와 일치합니다. 기관의 실명 인증을 뜻하지는 않습니다.' : '스키마가 같아도 발행자 신뢰를 자동으로 보장하지 않습니다.'}</p></div></div>
 <Tabs defaultValue="read"><TabsList variant="line"><TabsTrigger value="read">내용</TabsTrigger><TabsTrigger value="verify">검증 정보</TabsTrigger><TabsTrigger value="raw">원본</TabsTrigger></TabsList><TabsContent value="read"><h3>발행자</h3><button className="address-link mono" onClick={() => goWallet(a.attester)}>{a.attester}</button><h3>수신 지갑</h3><button className="address-link mono" onClick={() => goWallet(a.recipient)}>{a.recipient}</button><h3>도장 데이터</h3>{a.fields.length ? <div className="field-list">{a.fields.map(f => <div key={f.name}><span><strong>{f.name}</strong><small>{f.type}</small></span><code>{f.value}</code></div>)}</div> : <div className="notice">이 스키마의 데이터를 자동 해석하지 못했습니다. 원본 탭에서 확인하세요.</div>}<Info label="발급" value={date(a.time)}/><Info label="만료" value={a.expirationTime ? date(a.expirationTime) : '만료 기한 없음'}/>{a.revocationTime > 0 && <Info label="취소" value={date(a.revocationTime)}/>}<Info label="취소 가능" value={a.revocable ? '가능' : '불가능'}/>{a.refUID !== ZERO && <Info label="참조 도장 UID" value={a.refUID}/>}</TabsContent><TabsContent value="verify"><div className="checks"><Check label="EAS 레코드 존재" pass/><Check label="취소되지 않음" pass={a.revocationTime === 0}/><Check label="만료되지 않음" pass={!a.expirationTime || a.expirationTime > Date.now()/1000}/><Check label="Dojang 스키마" pass={a.dojang}/><Check label="현재 등록 발행자" pass={a.registeredIssuer}/></div><button className="secondary-button" onClick={() => goSchema(a.schema)}>스키마 상세 보기</button><Info label="조회 블록" value={String(a.checkedBlock ?? a.block ?? '—')}/>{a.checkedAt && <Info label="상태 확인 시각" value={new Date(a.checkedAt).toLocaleString('ko-KR')}/>}<div className="notice">유효 상태는 존재·만료·취소 조건을 나타냅니다. 사실의 진위, 발행자의 권한, 잔액 Merkle 경로는 해당 resolver와 서비스 정책을 함께 검증해야 합니다.</div>{a.tx && <a className="secondary-button" href={`${NETWORK.explorer}/tx/${a.tx}`} target="_blank" rel="noreferrer">발급 트랜잭션<ExternalLink size={14}/></a>}</TabsContent><TabsContent value="raw"><pre className="code-box">{JSON.stringify(a, null, 2)}</pre></TabsContent></Tabs>
 <div className="detail-actions"><button className="secondary-button" onClick={() => { const url = `${window.location.origin}/?view=explore&uid=${a.uid}`; navigator.clipboard.writeText(url).then(() => toast.success('도장 링크를 복사했습니다.')); }}>링크 복사</button><button className="secondary-button" onClick={() => downloadJSON(a, `dojang-${short(a.uid)}.json`)}><Download size={14}/>JSON 저장</button></div></> : null}
 </div></SheetContent></Sheet>;
}
function date(time: number) { return new Date(time * 1000).toLocaleString('ko-KR'); }
function Info({ label, value }: { label: string; value: string }) { return <div className="detail-info"><span>{label}</span><div><code>{value}</code>{value.startsWith('0x') && <CopyButton value={value}/>}</div></div>; }
function Check({ label, pass }: { label: string; pass: boolean }) { return <div>{pass ? <CheckCircle2 className="check-good" size={17}/> : <AlertCircle className="check-bad" size={17}/>}<span>{label}</span><Badge variant={pass ? 'success' : 'neutral'}>{pass ? '확인' : '미충족'}</Badge></div>; }
