'use client';
import { Copy,Fingerprint } from 'lucide-react';
import { toast } from 'sonner';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { short,type Attestation } from '@/lib/giwa';
export async function getData<T = any>(kind: string, params: Record<string, string> = {}): Promise<T> { const res = await fetch('/api/scan?' + new URLSearchParams({ kind, ...params })); const data = await res.json() as T & { error?: string }; if (!res.ok) throw new Error(data?.error ?? '해당 기록을 찾을 수 없습니다.'); return data; }
export function CopyButton({ value }: { value: string }) { return <button className="icon-button" aria-label="복사" onClick={() => navigator.clipboard.writeText(value).then(() => toast.success('복사했습니다.')).catch(() => toast.error('복사하지 못했습니다.'))}><Copy size={14} /></button>; }
export function Badge({ children, variant = 'neutral' }: { children: React.ReactNode; variant?: string }) { return <span className={'badge ' + variant}>{children}</span>; }
export function Status({ value }: { value: string }) { return <Badge variant={value === 'active' ? 'success' : value === 'revoked' ? 'danger' : 'neutral'}>{value === 'active' ? '유효' : value === 'revoked' ? '취소됨' : '만료됨'}</Badge>; }
export function ScanTable({ items, onSelect }: { items: Attestation[]; onSelect: (item: Attestation) => void }) { return <Table><TableHeader><TableRow><TableHead>도장 / UID</TableHead><TableHead>스키마</TableHead><TableHead>발행자</TableHead><TableHead>수신 지갑</TableHead><TableHead>발급 시각</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{items.map(item => <TableRow key={item.uid}><TableCell><button className="record-link mono" onClick={() => onSelect(item)}><span className="tiny-seal"><Fingerprint size={16} /></span>{short(item.uid)}</button></TableCell><TableCell><span className="schema-dot" />{item.schemaName}<span className="sub-label">{item.dojang ? 'Dojang schema' : 'EAS schema'}</span></TableCell><TableCell><span>{item.issuerName}</span><span className="sub-label mono">{short(item.attester)}</span></TableCell><TableCell className="mono">{short(item.recipient)}</TableCell><TableCell>{new Date(item.time * 1000).toLocaleDateString('ko-KR')}<span className="sub-label">{new Date(item.time * 1000).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })}</span></TableCell><TableCell><Status value={item.status} /></TableCell></TableRow>)}</TableBody></Table>; }
