import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const root='snaps/dojang-insights';
mkdirSync(root+'/dist',{recursive:true});
await build({entryPoints:[root+'/src/index.ts'],outfile:root+'/dist/bundle.js',bundle:true,format:'iife',globalName:'DojangSnap',footer:{js:'module.exports = DojangSnap;'},platform:'browser',target:'es2020',minify:true});
const manifest=JSON.parse(readFileSync(root+'/snap.manifest.json','utf8'));
manifest.source.shasum=createHash('sha256').update(readFileSync(root+'/dist/bundle.js')).digest('base64');
writeFileSync(root+'/snap.manifest.json',JSON.stringify(manifest,null,2)+'\n');
console.log('GIWA Snap bundle and manifest digest generated. Not published or installed.');
